### PR TITLE
feat: add fft support for fractional processes

### PR DESCRIPTION
**Pull request by dancixx**

### CODE REVIEW

**Comment by avhz** [comment]
Sorry, the stochastics module has been modified quite a bit to include time-dependent parameters so this conflict will need to be fixed before merging.

**Comment by dancixx** [comment]
@avhz should I change anything else?

**Comment by avhz** [comment]
Hi @dancixx, possibly just check/fix the build error and it should be good :)

**Comment by dancixx** [comment]
@avhz build issue is fixed :)

**Pull request merged**
