### PR TITLE
Feat: brownian bridge and merton jump diffusion processes

### PR DESCRIPTION
**Pull request by kinrezC**
- Adds `merton_jump_diffusion.rs` and `geometric_brownian_bridge.rs`
- Depends on #147

### CODE REVIEW

**Comment by Autoparallel** [comment]
We should also set up for a seeded jump process so we can have jumps be predictable and repeatable.

**Comment by avhz** [comment]
I've been wanting the Merton jump process for ages, this is awesome. Thank you. 
Adding bridges is also fantastic, cheers.

**Comment by avhz** [comment]
P.S. If you add new processes, please also slightly modify `./examples/stochastic_processes.rs` to include the new ones, and double check the generated plot as a sanity check.

**Comment by Autoparallel** [comment]
@avhz the bridge here doesn't land you exactly at the target endpoint. Do you prefer we do that? If so, it will require modifying the Euler-Maruyama which is fine.

As for how the jump is implemented, does it seem to adhere to your trait properly?

**Comment by avhz** [comment]
I suppose if it's off the endpoint simply due to a discretisation error its totally fine. 
If not, do you know the cause?

**Comment by kinrezC** [comment]
Cleaned up the PR, rebased off of main, and added the merton jump and brownian bridge examples.  Could you guys sanity check the merton jump results? It LGTM but I'd like a second opinion.  You can pull down my branch and mess around with the parameterizations, see if it returns expected results.

**Comment by kinrezC** [comment]
also if you could rerun the tests, looks like it failed on a module unrelated to this PR

**Comment by Autoparallel** [comment]
> I suppose if it's off the endpoint simply due to a discretisation error its totally fine.
> If not, do you know the cause?

It's off because it is using forward Euler and generating `value[t+1] = some_fn_of(value[t])`. So it gets close, but not exact.

If we did reimplement `euler_maruyama` for the bridge process explicitly, it'd just be a matter of an addition like: `if step == last_step { value[t+1] = final_value }`

**Comment by avhz** [comment]
Thanks a lot for this PR, super nice addition. 

P.S. I'm not too fussed about the slight end point error in the bridge, its your call if you want to fix it.

**Pull request merged**
